/**
 * Budget entity
 * Represents monthly spending limit
 */
export interface Budget {
  /** Unique identifier (auto-generated by IndexedDB) */
  id?: number;

  /** Month identifier in YYYY-MM format (e.g., '2025-10') */
  monthYear: string;

  /** Budget limit amount in NT$ (must be positive) */
  limit: number;

  /** Creation timestamp in ISO 8601 format */
  createdAt: string;

  /** Last update timestamp in ISO 8601 format */
  updatedAt: string;
}

/**
 * Budget creation input (omits auto-generated fields)
 */
export interface BudgetInput {
  monthYear: string;
  limit: number;
}

/**
 * Budget update input
 */
export interface BudgetUpdateInput {
  id: number;
  limit: number;
}

/**
 * Budget status with calculated values
 */
export interface BudgetStatus {
  /** Budget record */
  budget: Budget;

  /** Total expenses for the month */
  totalExpenses: number;

  /** Percentage of budget used (0-100+) */
  usagePercentage: number;

  /** Amount remaining (negative if exceeded) */
  remaining: number;

  /** Warning level: none, warning (80%), alert (100%+) */
  level: 'none' | 'warning' | 'alert';

  /** Optional message for user */
  message?: string;
}
