/**
 * Category type enum
 */
export type CategoryType = 'income' | 'expense';

/**
 * Category entity
 * Represents a spending or income classification
 */
export interface Category {
  /** Unique identifier (auto-generated by IndexedDB) */
  id?: number;

  /** Category display name (max 20 characters) */
  name: string;

  /** Category type: income or expense */
  type: CategoryType;

  /** Icon identifier (e.g., 'food', 'transport') */
  icon: string;

  /** Hex color code (e.g., '#22c55e') */
  color: string;

  /** True for predefined categories (cannot be deleted) */
  isDefault: boolean;

  /** Creation timestamp in ISO 8601 format */
  createdAt: string;
}

/**
 * Category creation input (omits auto-generated fields)
 */
export interface CategoryInput {
  name: string;
  type: CategoryType;
  icon: string;
  color: string;
}

/**
 * Category update input (all fields optional except id)
 */
export interface CategoryUpdateInput {
  id: number;
  name?: string;
  icon?: string;
  color?: string;
}

/**
 * Available icon identifiers
 */
export type CategoryIcon =
  | 'salary' | 'bonus' | 'investment' | 'other'       // Income icons
  | 'food' | 'transport' | 'shopping' | 'entertainment'
  | 'medical' | 'education' | 'housing' | 'pet'       // Expense icons
  | 'utilities' | 'insurance' | 'gift' | 'travel';

/**
 * Predefined color palette (WCAG AA compliant)
 */
export const CategoryColors = {
  // Income greens
  green600: '#16a34a',
  green700: '#15803d',
  green800: '#166534',
  green900: '#14532d',

  // Expense reds
  red600: '#dc2626',
  red700: '#b91c1c',
  red800: '#991b1b',
  red900: '#7f1d1d',
  red500: '#ef4444',
  red400: '#f87171',
  red300: '#fca5a5',
  red200: '#fecaca',

  // Custom category colors
  blue600: '#2563eb',
  purple600: '#9333ea',
  yellow600: '#ca8a04',
  orange600: '#ea580c',
  pink600: '#db2777',
  indigo600: '#4f46e5',
} as const;

export type CategoryColor = typeof CategoryColors[keyof typeof CategoryColors];
