/**
 * Transaction type enum
 */
export type TransactionType = 'income' | 'expense';

/**
 * Transaction entity
 * Represents a single financial record (income or expense)
 */
export interface Transaction {
  /** Unique identifier (auto-generated by IndexedDB) */
  id?: number;

  /** Transaction type: income or expense */
  type: TransactionType;

  /** Transaction amount in NT$ (must be positive) */
  amount: number;

  /** Transaction date in ISO 8601 format (YYYY-MM-DD) */
  date: string;

  /** Reference to category ID */
  categoryId: number;

  /** Optional user description (max 200 characters) */
  description?: string;

  /** Creation timestamp in ISO 8601 format */
  createdAt: string;

  /** Last update timestamp in ISO 8601 format */
  updatedAt: string;
}

/**
 * Transaction creation input (omits auto-generated fields)
 */
export interface TransactionInput {
  type: TransactionType;
  amount: number;
  date: string;
  categoryId: number;
  description?: string;
}

/**
 * Transaction update input (all fields optional except id)
 */
export interface TransactionUpdateInput {
  id: number;
  type?: TransactionType;
  amount?: number;
  date?: string;
  categoryId?: number;
  description?: string;
}

/**
 * Quick add transaction input (minimal fields)
 */
export interface QuickAddInput {
  amount: number;
  type?: TransactionType; // Defaults to 'expense'
  categoryId?: number;    // Defaults to default expense category
}

/**
 * Transaction filter criteria
 */
export interface TransactionFilters {
  /** Filter by date range */
  dateRange?: {
    start: string; // ISO 8601 date
    end: string;   // ISO 8601 date
  };

  /** Filter by transaction type */
  type?: TransactionType;

  /** Filter by category IDs (multiple selection) */
  categoryIds?: number[];

  /** Search text in description (case-insensitive) */
  searchText?: string;
}

/**
 * Simple filter interface for filter panel
 */
export interface TransactionFilter {
  search?: string;
  type?: TransactionType;
  categoryId?: number;
  startDate?: string;
  endDate?: string;
}

/**
 * Transaction sort criteria
 */
export interface TransactionSort {
  field: 'date' | 'amount' | 'category' | 'type';
  direction: 'asc' | 'desc';
}
